# Generated by Django 3.2.4 on 2021-08-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplainReg',
            fields=[
                ('complain_id', models.AutoField(primary_key=True, serialize=False)),
                ('complainee_fname', models.CharField(max_length=20)),
                ('complainee_lname', models.CharField(max_length=20)),
                ('dateofcomplain', models.DateField()),
                ('timeofcomplain', models.TimeField()),
                ('complainee_cnic', models.CharField(max_length=15)),
                ('complainee_contactno', models.BigIntegerField()),
                ('FIR_status', models.BooleanField(default=0)),
                ('crime_description', models.TextField(max_length=200)),
                ('victim_description', models.TextField(max_length=150)),
                ('email_address', models.EmailField(max_length=25)),
            ],
        ),
    ]
