# Generated by Django 3.2.4 on 2021-08-11 15:51

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_complainreg_complainee_cnic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complainreg",
            name="complainee_cnic",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="complainreg",
            name="complainee_contactno",
            field=models.CharField(max_length=11),
        ),
    ]
