# Generated by Django 3.2.4 on 2021-08-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210811_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesRecord',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('CrimeScene', models.CharField(max_length=50)),
                ('EVidence', models.CharField(max_length=50)),
                ('CaseStatus', models.BinaryField()),
                ('complain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.complainreg')),
            ],
        ),
        migrations.CreateModel(
            name='CriminalRecord',
            fields=[
                ('criminal_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Sentence', models.CharField(max_length=20)),
                ('CaptureStatus', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('BasicSalary', models.IntegerField()),
                ('Designation', models.CharField(max_length=30)),
                ('Ranking', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Work_force',
            fields=[
                ('officer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Officerfname', models.CharField(max_length=20)),
                ('Officerlname', models.CharField(max_length=20)),
                ('Officer_CNIC', models.CharField(max_length=15, unique=True)),
                ('Officer_email', models.CharField(max_length=25)),
                ('Officer_cellNo', models.BigIntegerField()),
                ('Officer_phoneNo', models.CharField(max_length=11)),
                ('Officer_DOB', models.DateField()),
                ('Officer_DOJ', models.DateField()),
                ('Officer_Education', models.CharField(max_length=27)),
                ('Temp_address', models.CharField(max_length=70)),
                ('Permanent_address', models.CharField(max_length=70)),
                ('MaritalStatus', models.CharField(max_length=10)),
                ('PostingNo', models.IntegerField()),
                ('Ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.designations')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectRecord',
            fields=[
                ('CNIC', models.CharField(max_length=15, primary_key=True, serialize=False, unique=True)),
                ('suspectlFname', models.CharField(max_length=20)),
                ('suspectLname', models.CharField(max_length=20)),
                ('suspect_DOB', models.DateField(default=None)),
                ('Height', models.CharField(max_length=6)),
                ('Education', models.CharField(max_length=20)),
                ('BloodGroup', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=60)),
                ('MaritalStatus', models.CharField(max_length=10)),
                ('Picture', models.ImageField(blank=True, upload_to='')),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.casesrecord')),
            ],
        ),
        migrations.CreateModel(
            name='PrisonerRecord',
            fields=[
                ('Prisoner_id', models.AutoField(primary_key=True, serialize=False)),
                ('CrminalCNIC', models.CharField(max_length=15)),
                ('DateOfTransfer', models.DateField()),
                ('TimeOftransfer', models.TimeField()),
                ('JailClass', models.CharField(max_length=6)),
                ('TransferStatus', models.BooleanField(default=0)),
                ('criminal_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.criminalrecord')),
            ],
        ),
        migrations.AddField(
            model_name='criminalrecord',
            name='CNIC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.suspectrecord'),
        ),
        migrations.AddField(
            model_name='criminalrecord',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.casesrecord'),
        ),
        migrations.AddField(
            model_name='casesrecord',
            name='officer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.work_force'),
        ),
    ]
