# Generated by Django 3.2.4 on 2021-08-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210811_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prisonerrecord',
            name='CrminalCNIC',
        ),
    ]
