# Generated by Django 3.2.5 on 2021-08-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_casesrecord_casestatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesrecord',
            name='complain_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.complainreg'),
        ),
    ]
