# Generated by Django 3.2.4 on 2021-08-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_casesrecord_complain_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalrecord',
            name='Sentence',
            field=models.CharField(max_length=25),
        ),
    ]
