# Generated by Django 3.2.4 on 2021-09-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_criminalrecord_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspectrecord',
            name='suspect_DOB',
            field=models.DateField(blank=True),
        ),
    ]
