# Generated by Django 3.2.4 on 2021-09-09 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_designations_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suspectrecord',
            name='case_id',
        ),
    ]
